name: MediaPlayer
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.0.1
  url_launcher: ^3.0.3
  audioplayers: ^0.7.8
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  video_player: ^0.10.1
 # http: ^0.12.0+2
  #youtube_player_flutter: 
  #cached_network_image: ^0.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/JOSh.gif
    - assets/Music3.gif
    - assets/Memories.jpg
    - assets/Calm.jpg
    - assets/Beats.jpg
    - assets/Hip2.jpg
    - assets/Pop3.jpg
    - assets/Alone-1.gif
    - assets/eminem.gif
    - assets/Marsh2.gif
    - assets/Johnwick.gif
    - assets/Sugar.jpg
    - assets/Neffex.jpg
    - assets/Serena-Safari.jpg
    - assets/Score.jpg
    - assets/Eminem21.gif
    - assets/oldtown.gif
    - assets/summer_pic.jpeg
    - assets/sea_waves.jpeg
    - assets/jungle2.jpg
    - assets/Large_bonfire.jpg
    - assets/Happy.jpg
    - assets/Danielle.jpg
    - assets/Postmalone.jpg
    - assets/Lose_Yourself.jpg
    - assets/drake.jpg
    - assets/Godzilla.jpg
    - assets/The_box.jpg
    - assets/Ava.jpg
    - assets/waykap.jpg
    - assets/martin.jpg
    - assets/black_hole.jpg
    - assets/music/Post Malone - Circles.mp3
    - assets/music/summer.mp3
    - assets/music/sea.mp3
    - assets/music/ES_Black Hole Serenade - White Drift.mp3
    - assets/music/ES_When I Get Sober (Instrumental Version) - waykap.mp3
    - assets/music/Eminem - Godzilla ft. Juice WRLD (Dir. by @_ColeBennett_).mp3
    - assets/music/Roddy Ricch - The Box [Official Music Video].mp3
    - assets/music/Maroon 5 - Memories (Official Video).mp3
    - assets/music/'DANCE MONKEY' - STREET SAX PERFORMANCE.mp3
    - assets/videos/Video_Godzilla.mp4
    - assets/videos/videoplayback.mp4
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
